services:
  - type: web
    name: catopmonitor-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --workers 4 --bind 0.0.0.0:$PORT app:app"
